# Build settings
markdown: kramdown
permalink: pretty
encoding: utf-8
port: 4010

exclude: [node_modules, gulpfile.js, package.json, js/bit.js, css/styles.css, ./bitwarden-website, less]
include: [".well-known"]
